-- MySQL Script generated by MySQL Workbench
-- Mon Nov  9 21:09:47 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`zona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`zona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`zona` (
  `Nombre` VARCHAR(45) NOT NULL,
  `CodZona` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Nombre`, `CodZona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Productos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `CodigoBarras` VARCHAR(45) NOT NULL,
  `Stock` INT NULL,
  `Tipo` VARCHAR(20) NOT NULL,
  `Precio` INT NOT NULL,
  `CodLocalizacion` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`CodigoBarras`, `Tipo`),
  INDEX `CodLocalizacion_idx` (`CodLocalizacion` ASC) VISIBLE,
  CONSTRAINT `CodLocalizacion`
    FOREIGN KEY (`CodLocalizacion`)
    REFERENCES `mydb`.`zona` (`CodZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `FechaPedido` DATE NOT NULL,
  `CodigoPedido` VARCHAR(45) NOT NULL,
  `Precio` INT NULL AUTO_INCREMENT,
  `Tipo` VARCHAR(20) NULL,
  PRIMARY KEY (`CodigoPedido`),
  INDEX `Tipo_idx` (`Tipo` ASC) VISIBLE,
  CONSTRAINT `Tipo`
    FOREIGN KEY (`Tipo`)
    REFERENCES `mydb`.`Productos` (`Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `Código de fidelizacion` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `DNI` VARCHAR(9) NOT NULL,
  `FechaNacimiento` DATE NOT NULL,
  `VolumenCompra` INT NULL AUTO_INCREMENT,
  `CodigoPedido` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Código de fidelizacion`),
  INDEX `CodigoPedido_idx` (`CodigoPedido` ASC) VISIBLE,
  CONSTRAINT `CodigoPedido`
    FOREIGN KEY (`CodigoPedido`)
    REFERENCES `mydb`.`Pedido` (`CodigoPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vivero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vivero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vivero` (
  `Nombre` VARCHAR(30) NOT NULL,
  `AforoMaximo` INT NULL,
  `Localizacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`),
  INDEX `Localizacion_idx` (`Localizacion` ASC) VISIBLE,
  CONSTRAINT `Localizacion`
    FOREIGN KEY (`Localizacion`)
    REFERENCES `mydb`.`zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Empleado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `DNI` VARCHAR(9) NOT NULL,
  `Sueldo` INT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `NSS` INT NOT NULL,
  `Cargo` VARCHAR(20) NULL,
  `NombreZonaTrabajo` VARCHAR(45) NOT NULL,
  `CodigoPedidoEncargado` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`, `NSS`, `Nombre`),
  INDEX `NombreZonaTrabajo_idx` (`NombreZonaTrabajo` ASC) VISIBLE,
  INDEX `CodigoPedidoEncargado_idx` (`CodigoPedidoEncargado` ASC) VISIBLE,
  CONSTRAINT `NombreZonaTrabajo`
    FOREIGN KEY (`NombreZonaTrabajo`)
    REFERENCES `mydb`.`zona` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CodigoPedidoEncargado`
    FOREIGN KEY (`CodigoPedidoEncargado`)
    REFERENCES `mydb`.`Pedido` (`CodigoPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
